#pragma config(Sensor, port3,  middleLightSensor, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  colorSensor,    sensorVexIQ_ColorHue)
#pragma config(Sensor, port8,  bumperSensor,   sensorVexIQ_Touch)
#pragma config(Sensor, port10, rightLightSensor, sensorNone)
#pragma config(Motor,  motor1,          ringHolder,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor2,          ringIntake,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          clawMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          pivotMotor,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma DebuggerWindows("Locals")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// RingmasterJoystick.c
const int kMinimumBatteryLvel = 6000;
int color, close;
int SPEED = -60;

task loadRings()
{
	setColorMode(colorSensor, colorTypeRGB_Hue_Reflected);
	while(true) {
		close = getColorProximity(colorSensor);

		if (close > 225){
			setMotorSpeed(ringIntake, 0);
			color = getColorHue(colorSensor); //Sets color variable
  		displayVariableValues(line5, color);
			displayVariableValues(line3, close);
  		displayMotorValues(line1, ringHolder);

			if ((color < 95)) { //if the color is red
   			setMotorTarget(ringHolder, 0, 127);
   			waitUntilMotorStop(ringHolder);
   			setMotorSpeed(ringIntake, 60);
   			wait1Msec(500);
  		}
	  	if ((color > 150) && (color <170)) { // if the color is blue
  	 		setMotorTarget(ringHolder, 360, -127);
   			waitUntilMotorStop(ringHolder);
   			setMotorSpeed(ringIntake, 60);
   			wait1Msec(500);
  		}
  	 	if ((color > 105) && (color < 140)) {
  			setMotorTarget(ringHolder, -360, 127);
  			waitUntilMotorStop(ringHolder);
  			setMotorSpeed(ringIntake, 60);
  			wait1Msec(500);
  		}
  	}
	} //while(true)
 } //loadrings



task main()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(pivotMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(ringHolder);
	resetMotorEncoder(ringIntake);
	resetGyro(gyroSensor);

	while(true){
		displaySensorValues(line1, colorSensor);
		tankControl(ChD, ChA, 10);

		if(getJoystickValue(BtnEUp) == 1)
		{
			setMotorSpeed(ringIntake, 60);
			startTask(loadRings);
		}

		if(getJoystickValue(BtnEDown) == 1)
		{
			stopTask(loadRings);
			setMotorTarget(ringHolder, 0 , 127);
			setMotorSpeed(ringIntake, -45);
			wait1Msec(500);
			stopMotor(ringIntake);
		}

		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.

		if(getJoystickValue(BtnRUp) == 1)
		{
			moveMotorTarget(clawMotor, -150, 75);
			waitUntilMotorMoveComplete(clawMotor);
			moveMotorTarget(clawMotor, 150, 75);
			moveMotorTarget(ringHolder, 360, 100);
		}

		if(getJoystickValue(BtnRDown) == 1)
		{
			moveMotorTarget(ringHolder, 360, 127);
			wait1Msec(1000);
		}
		//If the "F-Up" isn't pressed, but "F-Down" is, we'll set the motor to run forward.

		if(getJoystickValue(BtnFUp) == 1)
		{
				moveMotorTarget(ringHolder, 180, 127);
				waitUntilMotorStop(ringHolder);
				moveMotorTarget(pivotMotor, -1150, -100);
				waitUntilMotorStop(pivotMotor);
				wait1Msec(1000);
				moveMotorTarget(pivotMotor, 1200, 100);
				wait1Msec(2000);
				moveMotorTarget(ringHolder, 180, 100);
		}

		if(getJoystickValue(BtnFDown) == 1)
		{
				moveMotorTarget(ringHolder, 180, 127);
				waitUntilMotorStop(ringHolder);
				moveMotorTarget(pivotMotor, -1030, -100);
				waitUntilMotorStop(pivotMotor);
				wait1Msec(1000);
				moveMotorTarget(pivotMotor, 1000, 100);
				wait1Msec(2000);
				moveMotorTarget(ringHolder, 180, 100);
		}



//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

		if((getJoystickValue(BtnLUp) ==1) && (getJoystickValue(BtnLDown) == 1))
		{
			break;
		}
}

		while(true)
	{

	if (nImmediateBatteryLevel < kMinimumBatteryLvel)
      {
         playSound(soundTollBooth);
         break;
      }
     displayVariableValues(1, nImmediateBatteryLevel);

		displayMotorValues(line3, pivotMotor);
		tankControl(ChD, ChA, 10);
					if(getMotorOverTemp(clawMotor) == 1) {
				playSound(soundCarAlarm4);
}
		//If Button "E-Up" is pressed in, we'll set the Pivot motor to run in reverse.
		if(getJoystickValue(BtnRUp) == 1)
		{
			setMotorSpeed(clawMotor, -75);

			displayMotorValues(line1, clawMotor);
		}
		//If the "E-Up" isn't pressed, but "E-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnRDown) == 1)
		{
			setMotorSpeed(clawMotor, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(clawMotor, 0);
		}

		//If Button "R-Up" is pressed in, we'll set the Ring Intake motor to run in reverse.
		if(getJoystickValue(BtnEUp) == 1)
		{
			setMotorSpeed(ringIntake, 70);
		}
		//If the "R-Up" isn't pressed, but "R-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnEDown) == 1)
		{
			setMotorSpeed(ringIntake, -60);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(ringIntake, 0);
		}

				//If Button "F-Up" is pressed in, we'll set the Ring Holder motor to run in reverse.
		if(getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(ringHolder, 360, 127);
		}
		//If the "F-Up" isn't pressed, but "F-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnFDown) == 1)
		{
				setMotorTarget(ringHolder, 180, 127);
				waitUntilMotorStop(ringHolder);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
				resetMotorEncoder(ringHolder);
		}

						//If Button "L-Up" is pressed in, we'll set the Omni motor to run in reverse.
		if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(pivotMotor, -127);
		}
		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(pivotMotor, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(pivotMotor, 0);
		}
	}
}
