#pragma config(Sensor, port3,  middleLightSensor, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  colorSensor,    sensorVexIQ_ColorHue)
#pragma config(Sensor, port8,  bumperSensor,   sensorVexIQ_Touch)
#pragma config(Sensor, port10, rightLightSensor, sensorNone)
#pragma config(Motor,  motor1,          ringHolder,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor2,          ringIntake,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          clawMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          pivotMotor,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// RingmasterJoystick.c

int SPEED = -60;

task loadRings()
{
	while(true) {
  	int color = getColorHue(colorSensor); //Sets color variable
  	displayVariableValues(line5, color);

  	if ((color < 5)) { //if the color is red
    	moveMotorTarget(ringHolder, 360, 127);
    	waitUntilMotorStop(ringHolder);
    	//moveMotorTarget(ringIntake, -320, SPEED);
    	//waitUntilMotorStop(ringIntake);
    	wait(1, seconds);
    	moveMotorTarget(ringHolder, -360, -127); //reset to blue
    }

    if ((color > 83) & (color < 87)) { // if the color is green
    	moveMotorTarget(ringHolder, -360, -127);
    	waitUntilMotorStop(ringHolder);
    	//moveMotorTarget(ringIntake, -320, SPEED);
    	//waitUntilMotorStop(ringIntake);
    	wait(1, seconds);
    	moveMotorTarget(ringHolder, 360, 127); //reset to blue
    }

    if ((color > 168) & (color < 173)) { // if the color is Blue
    	//moveMotorTarget(ringIntake, -320, SPEED);
    	//waitUntilMotorStop(ringIntake);
    }
    setMotorTarget(ringHolder, 0 , 127);
   } //while(true)
   stopMotor(ringIntake);
 } //loadrings



task main()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(pivotMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(ringHolder);
	resetMotorEncoder(ringIntake);
	resetGyro(gyroSensor);

	repeat(forever){
		displaySensorValues(line1, colorSensor);
		tankControl(ChD, ChA, 10);
		if(getJoystickValue(BtnEUp) == 1) {
			setMotorSpeed(ringIntake, 60);
			startTask(loadRings);
		}
		if(getJoystickValue(BtnEDown) == 1) {
			stopTask(loadRings);
			setMotorTarget(ringHolder, 0 , 127);
			stopMotor(ringIntake);
		}

		if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(pivotMotor, -127);
		}
		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(pivotMotor, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(pivotMotor, 0);
		}
	}
}
